#!/bin/bash
set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[0;33m'; NC='\033[0m'

TEST_NAME="UC-ARGOCD-02: ApplicationSet Multi-Cluster"
NAMESPACE="argocd"
CHART_PATH="../../../../charts/common-argocd"
VALUES_FILE="../values/uc02-applicationset.yaml"
TOTAL_TESTS=0; PASSED_TESTS=0; FAILED_TESTS=0

pass() { echo -e "${GREEN}✅ PASS${NC}: $1"; PASSED_TESTS=$((PASSED_TESTS + 1)); TOTAL_TESTS=$((TOTAL_TESTS + 1)); }
fail() { echo -e "${RED}❌ FAIL${NC}: $1"; FAILED_TESTS=$((FAILED_TESTS + 1)); TOTAL_TESTS=$((TOTAL_TESTS + 1)); }
info() { echo -e "${BLUE}ℹ️  INFO${NC}: $1"; }
warn() { echo -e "${YELLOW}⚠️  WARN${NC}: $1"; }

cleanup() {
  helm uninstall argocd-appset-test -n $NAMESPACE 2>/dev/null || true
  kubectl delete applicationset multi-cluster-app -n $NAMESPACE 2>/dev/null || true
  kubectl delete application guestbook-dev -n $NAMESPACE 2>/dev/null || true
  kubectl delete namespace dev-apps 2>/dev/null || true
}
trap cleanup EXIT

echo -e "${BLUE}=================================================================${NC}"
echo -e "${BLUE}  $TEST_NAME${NC}"
echo -e "${BLUE}=================================================================${NC}"

# Check ArgoCD
echo ""
echo -e "${BLUE}=== Test 1: Verify ArgoCD Installation ===${NC}"
if kubectl get namespace argocd &> /dev/null; then
  pass "ArgoCD namespace exists"
else
  warn "ArgoCD not installed"
  exit 2
fi

if kubectl get deployment argocd-server -n argocd &> /dev/null; then
  pass "ArgoCD server installed"
else
  fail "ArgoCD server not found"
  exit 2
fi

# Check ApplicationSet CRD
if kubectl get crd applicationsets.argoproj.io &> /dev/null; then
  pass "ApplicationSet CRD exists"
else
  fail "ApplicationSet CRD not found (requires ArgoCD v2.6+)"
  exit 2
fi

# Install chart
echo ""
echo -e "${BLUE}=== Test 2: Create ApplicationSet ===${NC}"
if helm install argocd-appset-test $CHART_PATH -f $VALUES_FILE -n $NAMESPACE --wait --timeout 5m; then
  pass "Chart installed"
else
  fail "Installation failed"
  exit 1
fi

sleep 5

# Verify ApplicationSet
echo ""
echo -e "${BLUE}=== Test 3: Verify ApplicationSet Resource ===${NC}"
if kubectl get applicationset multi-cluster-app -n $NAMESPACE &> /dev/null; then
  pass "ApplicationSet resource created"
else
  fail "ApplicationSet resource not found"
fi

# Check generated Applications
echo ""
echo -e "${BLUE}=== Test 4: Verify Generated Applications ===${NC}"
info "Waiting for Applications to be generated..."
sleep 10

APPS=$(kubectl get applications -n $NAMESPACE -l "argocd.argoproj.io/application-set-name=multi-cluster-app" --no-headers 2>/dev/null | wc -l | tr -d ' ')
if [ "$APPS" -gt 0 ]; then
  pass "Applications generated by ApplicationSet (count: $APPS)"
  kubectl get applications -n $NAMESPACE -l "argocd.argoproj.io/application-set-name=multi-cluster-app" --no-headers 2>/dev/null || true
else
  warn "No Applications generated yet"
  info "Check ApplicationSet status: kubectl describe applicationset multi-cluster-app -n argocd"
fi

# Check dev Application specifically
echo ""
echo -e "${BLUE}=== Test 5: Verify Dev Application ===${NC}"
if kubectl get application guestbook-dev -n $NAMESPACE &> /dev/null; then
  pass "Dev Application created"
  
  DEV_SYNC=$(kubectl get application guestbook-dev -n $NAMESPACE -o jsonpath='{.status.sync.status}' 2>/dev/null || echo "Unknown")
  info "Dev Sync Status: $DEV_SYNC"
else
  warn "Dev Application not found (may require cluster registration)"
fi

# Summary
echo ""
echo -e "${BLUE}=== Summary ===${NC}"
echo "Passed: $PASSED_TESTS, Failed: $FAILED_TESTS"
kubectl get applicationset multi-cluster-app -n argocd 2>/dev/null || true
info "Note: Multi-cluster requires cluster secrets registered in ArgoCD"
[ $FAILED_TESTS -eq 0 ] && echo -e "${GREEN}✅ All tests passed${NC}" && exit 0
echo -e "${RED}❌ Some tests failed${NC}" && exit 1
