apiVersion: v1
kind: Namespace
metadata:
  name: ns-p1-daemonset
  labels:
    moai.forge.io/managed: "true"
    moai.forge.io/type: "application"
    moai.forge.io/owner: "platform-team"
    moai.forge.io/project: "forge-testing"
    moai.forge.io/environment: "test"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon
  namespace: ns-p1-daemonset
spec:
  selector:
    matchLabels:
      app: nginx-daemon
  template:
    metadata:
      labels:
        app: nginx-daemon
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
