apiVersion: v1
kind: Namespace
metadata:
  name: ns-p1-deploy-hpa-pdb
  labels:
    moai.forge.io/managed: "true"
    moai.forge.io/type: "application"
    moai.forge.io/owner: "platform-team"
    moai.forge.io/project: "forge-testing"
    moai.forge.io/environment: "test"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hpa-pdb
  namespace: ns-p1-deploy-hpa-pdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hpa-pdb
  template:
    metadata:
      labels:
        app: nginx-hpa-pdb
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nginx
  namespace: ns-p1-deploy-hpa-pdb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-hpa-pdb
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-nginx
  namespace: ns-p1-deploy-hpa-pdb
spec:
  minAvailable: 7
  selector:
    matchLabels:
      app: nginx-hpa-pdb
